using System.Collections.Generic;

namespace FrostheimSaga.Characters
{
    /// Represents a character (player or NPC) in Frostheim Saga.
    /// Generated by AI with stats, traits, and background.
    [System.Serializable]
    public class Character
    {
        public string Name;
        public int Age;
        public string Race;              // e.g. "Människa", "Alv", "Dvärg"
        public string CharacterClass;    // e.g. "Krigare", "Magiker", "Tjuv"
        public int Level;

        [System.Serializable]
        public class Stats
        {
            public int Strength;
            public int Dexterity;
            public int Constitution;
            public int Intelligence;
            public int Wisdom;
            public int Charisma;
        }

        public Stats Attributes;
        public string Background;        // Short backstory
        public List<string> Traits;      // Personality traits
        public List<string> Skills;      // e.g. "Svärdsstrid", "Alkemi"
        public List<string> Equipment;   // Starting gear
    }

    /// Helper class for parsing JSON response from AI.
    [System.Serializable]
    public class CharacterResponse
    {
        public Character character;
    }
}
